ACTIVE_ROUTE_TIMEOUT = int(3000)
NODE_TRAVERSAL_TIME = int(40)
MY_ROUTE_TIMEOUT = 2 * ACTIVE_ROUTE_TIMEOUT
NET_TRAVERSAL_TIME =2 * NODE_TRAVERSAL_TIME # * NET_DIAMETER
PATH_DISCOVERY_TIME = 2 * NET_TRAVERSAL_TIME